accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('', views.signup, name='signup'),
    path('', views.loginview, name='login'),
    path('', views.logoutview, name='logout'),
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path('create/', views.create, name='create'),
    path('<int:pk>/upvote', views.upvote, name='upvote'),    
    path('<int:pk>/downvote', views.downvote, name='downvote'), 
]

redditclone/urls.py
from django.contrib import admin
from django.urls import path, include

from posts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
    path('', views.home, name="home"),
    
]

accounts/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=200)
    url = models.TextField()
    pub_date = models.DateTimeField()
    author = models.ForeignKey(User, 
    on_delete=models.CASCADE,)    # To refer to models defined in another application we can use Foreign Key
    votes_total = models.IntegerField(default=0)
    

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout 

# Create your views here.

def signup(request):
    if request.method == 'POST':
        if(request.POST['password1'] == request.POST['password2']):
            try:
                user = User.objects.get(username=request.POST['username'])
                return render(request, 'accounts/signup.html', {'error':'Username can\'t be same'})
            except User.DoesNotExist:
                user = User.objects.create_user(request.POST['username'], password=request.POST['password1'])
                login(request, user)
                return render(request, 'accounts/signup.html')
        else:
            return render(request, 'accounts/signup.html', {'error':'Passwords didn\'t match'})
    else:
        return render(request, 'accounts/signup.html')


def loginview(request):
    if request.method == 'POST':
        user = authenticate(request, username=request.POST['username'], password=request.POST['password'])
        if user is not None:
            login(request, user)
            if 'next' in request.POST: 
                return redirect(request.POST['next'])
            return redirect('home')
        else: 
            return render(request, 'accounts/login.html', {'error':'Invalid Username and Password'})
    else:
        return render(request, 'accounts/login.html')

def logoutview(request):
    if request.method == 'POST':
        logout(request)
        return redirect('home')

posts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from .models import Post # "from . import models" then use models.Post() instead of only Post() in ln.12 & 24

# Create your views here.

@login_required    # shows views only if user is logged in
def create(request):
    if request.method == 'POST':
        if request.POST['title'] and request.POST['url']:
            post = Post()
            post.title = request.POST['title']
            if request.POST['url'].startswith('http://') or request.POST['url'].startswith('https://'):
                post.url = request.POST['url']
            else:
                post.url = 'http://' + request.POST['url']
            post.pub_date = timezone.datetime.now()
            post.author = request.user
            post.save()
            return redirect('home')
        else:
            return render(request, 'posts/create.html', {'error' : 'Error: You need to enter the title & url'})
    return render(request, 'posts/create.html')

def home(request):
    posts = Post.objects.order_by('-votes_total')
    return render(request, 'posts/home.html', {'posts' : posts})

def upvote(request, pk):
    if request.method == 'POST':
        post = Post.objects.get(pk=pk)
        post.votes_total += 1
        post.save()
        return redirect('home')

def downvote(request, pk):
    if request.method == 'POST':
        post = Post.objects.get(pk=pk)
        post.votes_total -= 1
        post.save()
        return redirect('home')

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}

<h1>Login</h1>

{% if error %}
<p style="color:rgb(56, 52, 52)">{{ error }}</p>
{% endif %}
<br/>
<br/>
<form method="POST" action="{% url 'accounts:login' %}">
    {% csrf_token %} 

    {% if request.GET.next %}
    <input type="hidden" name="next" value="{{ request.GET.next }}"
    {% endif %}
    Username : 
    <br/>
    <input type="text" name="username" />
    <br/>
    Password : 
    <br/>
    <input type="password" name="password" />
    <br/>
    <br/>
    <input class="btn btn-primary" type="submit" value="Login" />
    <br/>

</form>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}

<h1>Sign Up</h1>

{% if error %}
<p style="color:rgb(54, 49, 49)">{{ error }}</p>
{% endif %}
<br/>
<br/>
<form method="POST" action="{% url 'accounts:signup' %}">
    {% csrf_token %} 
    Username : 
    <br/>
    <input type="text" name="username" />
    <br/>
    Password : 
    <br/>
    <input type="password" name="password1" />
    <br/>
    Confirm Password :
    <br/>
    <input type="password" name="password2" />
    <br/>
    <br/>
    <input class="btn btn-primary" type="submit" value="Sign Up" />
    <br/>

</form>
{% endblock %}

accounts/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Reddit</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
        <script src='https://kit.fontawesome.com/a076d05399.js'></script>
    </head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-color" style="background-color: rgb(0, 94, 110);">
      <a class="navbar-brand" href="{% url 'home' %}" style="color:whitesmoke;font-weight: 80; font-size: 30px;">Reddit</a>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="nav navbar-nav ml-auto">
            {% if user.is_authenticated %}           
                <li><a class="nav-link" href="#" onClick="document.getElementById('logout').submit()">LogOut</a></li>
                  <form id="logout" method="POST" action="{% url 'accounts:logout' %}">
                      {% csrf_token %} 
                      <input type="hidden">
                  </form>
            {% else %}
              <li><a class="nav-link" href="{% url 'accounts:signup' %}">Sign Up</a></li>
              <li><a class="nav-link" href="{% url 'accounts:login' %}">Login </a></li> 
            {% endif %}
          </ul>
        </div>
      </nav>
    
    <div class="container bg-light">
        {% block content %}
        {% endblock %}
    </div>

</body>
</html>

posts/templates/posts/create.html
{% extends 'base.html' %}

{% block content %}

<h1>Make a Post</h1>

{% if error %}
<p style="color:rgb(122, 10, 10)">{{ error }}</p>
{% endif %}
<br/>
<form method="POST" action="{% url 'posts:create' %}">
    {% csrf_token %} 

    Title : 
    <br/>
    <input type="text" name="title" />
    <br/>
    Post url :
    <br/>
    <input type="text" name="url" />
    <br/>
    <br/>
    <input class="btn btn-primary" type="submit" value="Post" />
    <br/>

</form>

{% endblock %}

posts/templates/posts/home.html
{% extends 'base.html' %}

{% block content %}
<h3> Welcome to Home Page</h3> 

<a href="{% url 'posts:create' %}" class="btn btn-primary btn-lg bg-info">New Post !</a>

<br/>
<br/>
{% for post in posts.all %}

<table>
    <tr>
        <td><a class="nav-link" href="#" onClick="document.getElementById('upvote{{ post.id }}').submit()"><i class='fas fa-angle-double-up' style='font-size:20px'></i></a></td><td> {{ post.votes_total }} </td><td><a class="nav-link" href="#" onClick="document.getElementById('downvote{{ post.id }}').submit()"><i class='fas fa-angle-double-down' style='font-size:20px'></i></a></td>
        <td style="padding-left: 20px;"><a href="{{ post.url }}">{{ post.title }}</a><br/>{{ post.pub_date }} by {{ post.author }}</td>
    </tr>
</table>

<form id="upvote{{ post.id }}" method="POST" action="{% url 'posts:upvote' post.id %}">
    {% csrf_token %}
    <input type="hidden">
</form> 
<form id="downvote{{ post.id }}" method="POST" action="{% url 'posts:downvote' post.id %}">
    {% csrf_token %}
    <input type="hidden">
</form>  
<br/>
<br/>

{% endfor %}
{% endblock %}